### ISSUE TITLE
Filter is a bit weird

### ISSUE THREAD

**Issue by denbatte** [IbeVanmeenen/KunstmaanBundlesCMS#13]
If you open the filter tab you see a dropdown with the text filter on. I personally find this a bit weird because the "filter on" is not really a option.

Wouldn't it be more clear to have a text like "No filters defined" with a "+ add filter" button below to add the dropdown without the "filter on option" in it?

Just come and ask if you have no clue at what i'm talking about :)

*edit: typo's

**Comment by IbeVanmeenen** [comment]
This is a bit like "choose ...".
Your solution just adds clicks needed for action to happen.
