### ISSUE TITLE
Navigation items disappear

### ISSUE THREAD

**Issue by dbeerten** [IbeVanmeenen/KunstmaanBundlesCMS#14]
When the dropdown "Modules" in the mobile navigation is opened, some navigation items disappear.

![screen shot 2015-02-26 at 11 01 53](https://cloud.githubusercontent.com/assets/5577291/6389722/ee124a56-bda6-11e4-868a-983c06b7b8eb.png)
- User & Logout are not visible

**Comment by IbeVanmeenen** [comment]
Default bootstrap - Scroll available
