### ISSUE TITLE
Lines and arrows of the tree are not aligned nicely, there are gaps in the lines and not everything feels retina

### ISSUE THREAD

**Issue by roderik** [IbeVanmeenen/KunstmaanBundlesCMS#29]
![screenshot 2015-03-07 08 03 55](https://cloud.githubusercontent.com/assets/16780/6540506/c8a512e8-c4a0-11e4-944d-28e9fc6ec32f.png)

**Comment by roderik** [comment]
this is a nice look, unfortunately not retina. http://www.orangehilldev.com/jstree-bootstrap-theme/demo/

**Comment by IbeVanmeenen** [comment]
Made more like theme + fully retina (svg)
