### ISSUE TITLE
Filter drop down could be "nicer"

### ISSUE THREAD

**Issue by roderik** [IbeVanmeenen/KunstmaanBundlesCMS#30]
It's kind of bug and clunky. Is this the native look?

![screenshot 2015-03-07 08 06 26](https://cloud.githubusercontent.com/assets/16780/6540508/f7aefce8-c4a0-11e4-8cbd-0955b558f6d1.png)

**Comment by IbeVanmeenen** [comment]
"Bootstrap Native" ... Should be looked at when new design is ready
