### ISSUE TITLE
Attachment to the tabs

### ISSUE THREAD

**Issue by roderik** [IbeVanmeenen/KunstmaanBundlesCMS#31]
There is a gap on the top of pages that should not be there. The gap is not there in media and it's much nicer.

![screenshot 2015-03-07 08 08 13](https://cloud.githubusercontent.com/assets/16780/6540523/69ab9f22-c4a1-11e4-8330-f4662385294e.png)

![screenshot 2015-03-07 08 09 21](https://cloud.githubusercontent.com/assets/16780/6540526/6dfe74c8-c4a1-11e4-9559-a80cef91dd95.png)

**Comment by IbeVanmeenen** [comment]
Still think it's a bit weird that it sticks to the tab. Then it looks like the content below doesn't belong to the tab anymore... Just place +1 if you really really wantz it, then I will do it :)

**Comment by IbeVanmeenen** [comment]
@roderik

**Comment by kimausloos** [comment]
I like the media (without gap) a bit better

**Comment by IbeVanmeenen** [comment]
Updated
