### ISSUE TITLE
Add jquery.min.map

### ISSUE THREAD

**Issue by roderik** [IbeVanmeenen/KunstmaanBundlesCMS#43]
![screenshot 2015-03-07 10 06 56](https://cloud.githubusercontent.com/assets/16780/6540807/ca17d92e-c4b1-11e4-92cb-46bf81c7deb2.png)

**Comment by IbeVanmeenen** [comment]
Source map: A way to map a combined/minified file back to an unbuilt state.

Will add unminified version of jquery for dev (as this error is only triggerd while devtools are open, and we minify the js anyway for prod)
